### ISSUE TITLE
Colorful output

### ISSUE THREAD

**Issue by seaneagan** [google/grinder.dart#100]
Specifically:

* distinguish output from grinder itself from task output
* display errors in red, warnings in yellow.
  * Should be supported in unscripted soonish: https://github.com/seaneagan/unscripted/issues/3
* nicer help output
  * unscripted has semantically highlighted (and automated) help output.

**Comment by devoncarew** [comment]
We have it, but do have issues with not always being able to detect an interactive terminal.
