### ISSUE TITLE
Ability to export tasks from other libraries

### ISSUE THREAD

**Issue by seaneagan** [google/grinder.dart#104]
```dart
// useful_tasks.dart

@Task(description: 'Useful.')
useful(GrinderContext context) {}

@Task(description: 'Also useful.', depends: const [useful])
alsoUseful(GrinderContext context) {}
```

```dart
// tool/grind.dart';
import 'package:useful_tasks/useful_tasks.dart';
export 'package:useful_tasks/useful_tasks.dart';

main(args) => grind(args);

@Task(depends: const [useful, alsoUseful])
build(GrinderContext context) {}
```

You cannot depend on tasks you do not export.

If you don't actually want to call the tasks by themselves, then you just call them within your task instead of depending on them:

```dart
// tool/grind.dart';
import 'package:useful_tasks/useful_tasks.dart';

main(args) => grind(args);

@Task()
build() {
  useful(context);
  alsoUseful(context);
  // ...
}
```

**Comment by devoncarew** [comment]
Cool.

From experience with Ant scripts however (which may or may not translate over), this may not be a common use case. I suspect that the tasks will all be defined in the user's single script. Those tasks will likely be non-trivial functions, with will call out to other libraries using normal dart mechanisims. When they do need to take tasks from another grind script wholesale (at least for ant), you'll often just shell out to it.

**Comment by seaneagan** [comment]
You may be right, as most tasks will probably need project-specific configuration.  But it might also be useful just as a way to split up your tasks into multiple files, since some people (e.g. me) much prefer using `export` to `part`.
