### ISSUE TITLE
Analyze grinder file produced by `pub run grinder:init`

### ISSUE THREAD

**Issue by seaneagan** [google/grinder.dart#108]
As long as the output of `pub run grinder:init` is static, it'd be nice to keep it in an actual dart file, so that we can get analysis warnings/errors in it without having to actually run.  I don't think it's possible to get the source of an imported library using `dart:mirrors`, so I think we'd have to wait for http://dartbug.com/21020 or use some workaround for that.

However, if we foresee the output becoming dynamic (e.g. adding a library name), then we'd need to add a test to actually run the command and run the analyzer on the output.

We could run other tests on the produced grinder file as well, not sure what.

**Comment by devoncarew** [comment]
+1 to analyzing the `init` output as part of the build. We do something like this for stagehand, and it has caught issues. Nice to have safety nets :)
