### ISSUE TITLE
Confusing convention

### ISSUE THREAD

**Issue by zoechi** [google/grinder.dart#121]
Why does `pub global run grinder` expect `tool/grind.dart` but `pub run grinder` expect `bin/grinder.dart` to exist?

**Comment by seaneagan** [comment]
`pub run grinder` is actually not supported, it should be `pub run grinder:grind`.  The README currently says `pub global run grind`, which is also incorrect.  Also see http://dartbug.com/22129.  And `pub global run grinder` will be deprecated in the [next version](https://github.com/google/grinder.dart/milestones/0.7.0).  You can use `pub global run grinder:grind` or just `grind`.  See https://github.com/google/grinder.dart/commit/6b8f7614ff9b0e71545e4130a79adccaf849f834.  It would be nice to have the executable and package name match to make the commands shorter.

In any case, your grinder file should always be at 'tool/grind.dart'.  Sorry for the confusion!

**Comment by devoncarew** [comment]
Yup, we haven't released for a little while (grinder's undergoing refactoring), but both of those scripts in the current codebase point to `tool/grind.dart`.

**Comment by zoechi** [comment]
Great to hear. 
Grinder seems to be great for automation but currently it's difficult getting started.

**Comment by devoncarew** [comment]
I tweaked the readme a bit; suggestions for clarify or simplifying getting started w/ grinder are welcome!
