### ISSUE TITLE
gzip

### ISSUE THREAD

**Issue by cgarciae** [google/grinder.dart#124]
I've been told that `grinder` can be used to *gzip* files automatically after each build but I don't know ANYTHING about gzipping or grinder. Can you give me a very basic "hello gzip" example to get started?

Thanks!

**Comment by zoechi** [comment]
Basically you can do everything from a grinder task what you can do in Dart code

```bash
pub global activate -s git git@github.com:google/grinder.dart.git
```
*pubspec.yaml*

```yaml
  grinder:
    git: git@github.com:google/grinder.dart.git
```

*tool/grind.dart*
```dart
import 'package:grinder/grinder.dart';
//import 'package:grinder/grinder_files.dart';

main(List<String> args) => grind(args);

@Task()
void init(GrinderContext context) => defaultInit(context);

@Task()
void clean(GrinderContext context) => defaultClean(context);

@Task()
@Depends(init)
void build(GrinderContext context) {
   runProcess(context, 'gzip', arguments: ['argument1', 'argument2']);
}
```

Execute the task with
```bash
grind build
```
or if `~/.pub-cache/bin/` is not in your path
```
dart tool/grind.dart build
```


[Here](https://github.com/google/grinder.dart/blob/master/lib/grinder_files.dart#L21) are some nice ideas but not yet implemented :-/ 

You could do this with a plain Dart script as well but when build becomes more complex it's probably easier using Grinder. The package contains for example nice methods for handling sets of files, and others.

**Comment by zoechi** [comment]
What I have seen in other related threads, usually the server does this automatically if everything is set up properly. Is this still a useful feature?

**Comment by devoncarew** [comment]
I think this is something user's can implement in their scripts - it doesn't need to be built into grinder itself.
