### ISSUE TITLE
just curious: why no testing on Windows via CI server?

### ISSUE THREAD

**Issue by guillermooo** [google/grinder.dart#125]
Now that's possible for OSS projects to use at least a Windows-based CI server, I was wondering why not use that for this and other Dart projects?

**Comment by seaneagan** [comment]
Which windows CI platform would you recommend?  It seems [AppVeyor](http://www.appveyor.com/) is the most popular at the moment.  Grinder uses travis, which does not ([yet](https://github.com/travis-ci/travis-ci/issues/216)) support windows.

**Comment by guillermooo** [comment]
AppVeyor is the one I use for my project (for example, the [Dart plugin for ST](https://github.com/guillermooo/dart-sublime-bundle)) and works really well (and it's getting faster).

I could take a look at adding the required config file for it.

**Comment by devoncarew** [comment]
This came up in conversation in the office yesterday. I don't really have any experience with CIs for windows, but would love to have the test visibility into windows for my projects. cc'ing @danrubel

**Comment by guillermooo** [comment]
BTW, I've started this, but I should get more methodical:

https://github.com/guillermooo-forks/grinder.dart/commits/add-appveyor-config

**Comment by devoncarew** [comment]
Cool! I'm excited to see if the windows CI uncovers any corss-platform issues w/ grinder.

**Comment by guillermooo** [comment]
After a cursory glance at the Travis setup, I think Travis is running the tests without `pub get`ting deps? Is that so? I tried locally on my Win PC the same thing and got errors. After pulling the deps, the tests passed.

**Comment by devoncarew** [comment]
The Dart config for travis runs `pub get` automatically before the grinder specific shell script gets ahold of it. So, it's already all set up for us.

**Comment by guillermooo** [comment]
Ah, got it.
