### ISSUE TITLE
Support for additional arguments for browser tests

### ISSUE THREAD

**Issue by zoechi** [google/grinder.dart#127]
examples
`content_shell --dump-render-tree some_test.html`
`chrome --allow-file-access-from-file some_test.html`
Even better would be have https://github.com/dart-lang/unittest/issues/23

**Comment by seaneagan** [comment]
I'm hoping to add task-specific command-line args, see #116.

I assume you will prefer to use the unittest runner via a grinder `test` task or similar, in which case it depends how that accepts these options, I wonder if they can be in [the config file](https://github.com/dart-lang/unittest/issues/46).

**Comment by zoechi** [comment]
Package level config file is probably to coarse-grained. I hope they will add additional configuration options for at list single test files. If the task-runner from the unittest package is used this issue might be redundant. I hope there will be a good integration.

**Comment by zoechi** [comment]
I think this can be closed. This is something the test package should provide.
