### ISSUE TITLE
delete tools\appveyor.ps1

### ISSUE THREAD

**Issue by guillermooo** [google/grinder.dart#134]
I think we forgot to delete it after the appveyor.yml refactoring.

**Comment by devoncarew** [comment]
kk, will delete.

I do like having a simple bootstrap file in the project root (.travis.yml, appveyor.yml), and having the bulk of the work done in `tool/`. The `appveyor.ps1` file seemed like it needed a lot of hand-holding to do work however; after every potential failing command we needed to check to see if it failed. And, having separate `tool/appveyor.ps` and `tool/travis.sh` files meant that there was duplication in the build code.

Probably the best solution is to have tiny config files at the project root, and have a common, shared build file in (written in dart) in `tool/`.

**Comment by guillermooo** [comment]
Unfortunately, when using PowerShell, Appveyor will only report failures if the script throws. Returning non-zero exit code isn't enough... Hence the need for checking every external command's success. This is kind of annoying.

I usually stay away from CMD if I can, but setting a couple env vars is tolerable. Anything more complicated than that, and I usually go for PS.

Agreed about consolidating common code and keeping yml files lean.

BTW, if Appveyor and Travis accept the .yaml extension, we'd have consistency in file names too (pubspec.yaml vs the rest)... Minor thing, but jumps at me every time.

**Comment by devoncarew** [comment]
done: https://github.com/google/grinder.dart/commit/1509eba9326045575543bc0c189806ed2325eebb
