### ISSUE TITLE
Consider baking in defaultInit to every grinder script

### ISSUE THREAD

**Issue by seaneagan** [google/grinder.dart#137]
Does every grinder script want to do what defaultInit is currently doing which is checking that the script is run from the project root?  If so, it would be nice to run that check automatically before any tasks are run, and obviated the need for everyone creating an `init` task.

**Comment by devoncarew** [comment]
I think it's good practice. But, is there a good use case for not having the check, and if so, how do we handle that case? Have an optional named param in `grind()`?

**Comment by zoechi** [comment]
If there is an init tasks in the script just use this instead of the default?

**Comment by devoncarew** [comment]
Having `init`'s functionality built into the `grind()` call would save 9 lines on the `build.dart` script for this project...
