### ISSUE TITLE
Use stack_trace package to improve stack traces

### ISSUE THREAD

**Issue by seaneagan** [google/grinder.dart#146]
Some stack trace beautifying was done in #142.  I think use `Chain.capture` and probably `Chain.terse` to improve this further:

https://pub.dartlang.org/packages/stack_trace

**Comment by zoechi** [comment]
+1  (for Chain.capture and Chain.terse)
I just recently discovered how much more useful the generated stack-traces are. 
pub, test and probably others are using it already.

**Comment by zoechi** [comment]
This would also need a CLI argument to disable. Sometimes stack frames are filtered out, which shouldn't be which can make debugging quite cumbersome.

**Comment by seaneagan** [comment]
Hmm, probably just `--verbose` (see #101).

Did you file a bug with the stack_trace package, or is it not something that can be fixed?

**Comment by zoechi** [comment]
Didn't create a bug report, I wasn't sure if it's a bug. It seems to filter all SDK code. AFAIR I run into this with an invalid date string in `DateTime.parse('invalid')` which failed somewhere inside `DateTime` but the stack trace didn't reveal the position. The `test` package added a flag to disable `Chain.terse`, therefore I concluded this is the way to go.

**Comment by devoncarew** [comment]
Happy to take PRs for this one. Closing in the meantime.
