### ISSUE TITLE
Validate tasks either have dependencies or a function

### ISSUE THREAD

**Issue by seaneagan** [google/grinder.dart#152]
A task should always have some logic to run, either from other tasks, or its own.  This should be checked in the constructor.

**Comment by devoncarew** [comment]
Should this be a hard failure or a warning? If we detect cycles in the task deps we do a hard failure. A task which just isn't very useful - perhaps mid-refactoring - might be a less severe issue.

**Comment by seaneagan** [comment]
I thought is would be a hard failure to protect against someone thinking they are running a task, but in actuality, the task function was null, so nothing occurred.  It is not an issue with `@Task` annotated methods.  Only with programmatically added tasks or @Task annotated properties where the property is null.  I just wanted to bring it up now since it would technically be a breaking change.  I'd be fine with a warning though too if you think that's sufficient.

**Comment by devoncarew** [comment]
I can't think of a use case for no function _and_ no deps; an error sounds good.
