### ISSUE TITLE
Refactor PubApplication

### ISSUE THREAD

**Issue by seaneagan** [google/grinder.dart#153]
@devoncarew This is for the `PubApplication` class added in #71.  This doesn't need to block 0.7.0, but labeled as such so we can at least discuss it first:

* I liked the original shorter name `PubApp` better, no need to spell out `Application`.
* `isInstalled()` should be a getter, possibly renamed to `isActivated`.
* It should allow running any cli app from the package, not just the same named one.  The name `PubApplication` suggests it should be a constructor parameter (e.g. `executable: 'foo'`), and not a `run` parameter, in which case `isInstalled` should check the `pub global list` output to see if the individual script is installed ([once that is supported](http://dartbug.com/20641)).  But it's then weird to `activate()` or `update()` an individual script, so maybe change their name to `activatePackage` / `updatePackage`.  Probably also need to add `packageName` along-side `appName`.
* `pub run` has some advantages over `pub global run`.  Particularly matching the version of the package containing the script with the version used by the local package.  It should be supported as well.  Perhaps it can be an interface with (private) implementations for both global and local packages.  It can have an `isGlobal` property which is set by `PubApp.global` and `PubApp.local` constructors.  But `PubApp.activate()` doesn't make sense for local apps ([at least yet](https://docs.google.com/document/d/1lvbzyivCejhTuHLG4WI3YVThbQqJhPUrwajwTC-sXWU)), so maybe make it private for now, and just rely on it being done as part of `PubApp.run`?  Or just make it a no-op.  `PubApp.update` could potentially run `pub upgrade` (in which case, rename to `upgrade`?).  `PubApp.isInstalled` should check whether the script's containing package is in the pubspec.lock, and use the version found there to check the pub cache for the individual script existing in /bin.

**Comment by devoncarew** [comment]
> I liked the original shorter name PubApp better, no need to spell out Application.

+1. I had some trouble differentiating the name from the tuple returned from PubGlobal.list(), which I've now just called `AppVersion`.

> isInstalled() should be a getter, possibly renamed to isActivated.

+1

> It should allow running any cli app from the package, not just the same named one.

What if the `run()` method takes an optional named param, for the script name? So the simple case of:
```
PubApp grinder = new PubApp('grinder');
grinder.run('foo');
```
works, and the less common case of:
```
PubApp grinder = new PubApp('grinder');
grinder.run('foo', script: 'init'); // or 'grinder:ini'?
```
also works.

> pub run has some advantages over pub global run.

I hardly ever use just `pub run` myself. I think we could support this using named constructors; so `PubApp.global` or `PubApp.local`. Then, PubApp methods that didn't make sense in the context of local apps could be no-ops.

Hmm, re-reading your comments, you do suggest PubApp.global and PubApp.local constructors. sgtm :)

I'm not invested in the name `update` vs `upgrade` - either sounds fine. I do have concerns about the PubApp running `pub upgrade` on the local package version; I suspect that that would be unexpected behavior. `update` could just be a no-op for local apps. Thoughts?

**Comment by seaneagan** [comment]
> I had some trouble differentiating the name from the tuple returned from PubGlobal.list(), which I've now just called `AppVersion`.

`pub global list` will soon [return the script names](http://dartbug.com/20641) as well.  Perhaps we can add `PubApp.version` and `PubApp.scripts` getters, and `PubGlobal.list()` can return a `List<PubApp>`?

It might make sense to have the versions be represented as [pub_semver](https://pub.dartlang.org/packages/pub_semver) `Version`s instead of plain Strings.

> What if the `run()` method takes an optional named param

Definitely agree with making the param optional.  I tend to think of a `PubApp` being a single script, but I can get used to it representing the entire package full of scripts, especially since that facilitates the suggestion above about having a `PubApp.scripts` getter.

> I hardly ever use just `pub run` myself.

I know the pub maintainers are pushing folks to use `pub run` as much as possible based on the version agreement argument.  It's not a big problem for grinder since `grind` merely forwards to a local script which then uses the same version of `grinder` as the project.  I filed #154 to track adding a `Pub.run` method.

> I'm not invested in the name `update` vs `upgrade` - either sounds fine. I do have concerns about the PubApp running `pub upgrade` on the local package version; I suspect that that would be unexpected behavior.

Yeah, running `pub upgrade` was definitely a terrible idea :).  Keeping `update` is better then.

> `update` could just be a no-op for local apps. Thoughts?

sgtm

**Comment by devoncarew** [comment]
>  I tend to think of a PubApp being a single script

Ok, so if PubApp represents a single app - a package and script combination - we could then

- put that info in the ctor (`PubApp.global(String packageName, {String scriptName})`)
- not have the script param in the `run` method

**Comment by seaneagan** [comment]
That was my original thought, but then its weird to `activate()` / `update()` from something that represents a single script.  So I think I like putting the `script` parameter in `run` better after all.  The scripts provided by a package are probably all closely related enough to think of them as a single "app".  And they are versioned in unison etc. as well.

**Comment by devoncarew** [comment]
kk, makes sense.

**Comment by zoechi** [comment]
Is there a way in PubApplication for custom error handling?
The doc-comment doesn't tell anything about the behavior.
Is all it does to fail the task when `exitCode != 0`?

I tried to create a `check` tasks which runs `tuneup check`, the linter and I also want to check if the source is properly formatted.

`dartformat -n .` doesn't change the exitCode yet when there are issues but it prints a list of files which would need to be fixed.
I think there should be a way to handle the exit code in the task (only fail if `exitCode > 3` for example) and also to being able to subscribe to the stdout/stderr of the process would be great (see also dart-lang/dart_style#225)

**Comment by seaneagan** [comment]
We should just have `run` return the `ProcessResult`.  Do we want to have an async method as well?  If so, it should probably be `Future<ProcessResult> run(...)` and `ProcessResult runSync(...)` to match dart:io conventions.

**Comment by zoechi** [comment]
Sounds great!

**Comment by seaneagan** [comment]
Filed #156 to track returning a `ProcessResult` in general when running processes.

**Comment by seaneagan** [comment]
Also, we need to allow passing a version to the `PubApp.global` constructor.  As noted above, this *could* be a version from [pub_semver](http://dartbug.com/dart-lang/pub_semver).

**Comment by seaneagan** [comment]
Or maybe it gets passed to the `activate()` method (and to `Pub.global.activate` underneath).

**Comment by devoncarew** [comment]
Largely addressed -
