### ISSUE TITLE
Analyzer.analyzeFiles reports error on part files

### ISSUE THREAD

**Issue by zoechi** [google/grinder.dart#155]
I'm not sure where this should be fixed.
I also filed http://dartbug.com/23049 and https://github.com/dart-lang/linter/issues/82

**Comment by devoncarew** [comment]
You can also do this:
```dart
PubApplication tuneup = new PubApplication('tuneup');
tuneup.run(['check']);
```
Which will do the right thing wrt part files. It also knows which directories do and don't contain dart files.

**Comment by devoncarew** [comment]
The `Analyzer` class is a straight wrapper around the `dartanalyzer` command; if `dartanalyzer` fails, the first one will as well...

**Comment by zoechi** [comment]
Great, thanks for the hint!
I also wanted to add that removing the init task and the GrinderContext argument makes my grind files much easier to read. 
I already enjoy some other improvements and soon the new `PubApplication` :-)
