### ISSUE TITLE
runProcess and runProcessAsync should return the ProcessResult

### ISSUE THREAD

**Issue by seaneagan** [google/grinder.dart#156]
I like the behavior of checking the exit code and throwing an exception if non-zero. and automatically logging the stdout and stderr.  But the caller may still want to inspect what happened.  So it would be nice if `runProcess` returned it.  For `runProcessAsync` we'd need to construct a `ProcessResult` manually.  There's currently [no constructor](http://dartbug.com/23070), but we can just write our own class which `implements ProcessResult`.

Also, maybe the exception that's thrown should have an `exitCode` field to allow inspection, e.g. `NonZeroExitCodeException`.

Also, is grinder sync by default i.e. adds `Async` to async versions of APIs rather than `Sync` to sync versions of APIs ala dart:io?  I'm fine either way, just wanted to bring it up.

**Comment by devoncarew** [comment]
I like the default behavior of throwing on errors - it lets simple scripts stay simple. But allowing callers to get access to the returned process info makes sense, as well somehow intercepting the default throw-on-error behavior.

**Comment by zoechi** [comment]
Would a try/catch int the custom task work?

**Comment by devoncarew** [comment]
I think either. The try/catch might be better, as we wouldn't have to plumb a new arg down through several different methods.
