### ISSUE TITLE
Shorten runProcess[Async]/runDartScript

### ISSUE THREAD

**Issue by seaneagan** [google/grinder.dart#161]
In the spirit of `log`, `fail`, `copy`, `delete`, might be nice to shorten up `runProcess`, `runProcessAsync`, and `runDartScript`.  `run` / `runAsync` seems clear enough to me without `Process`:

`run('dart', ['--version'])`

For `runDartScript` we could crib off of e.g. `Pub.run`, `Dart2js.compile`, etc. and have a `Dart.run`.

`Dart.run('tool/foo.dart')`

 @devoncarew

**Comment by devoncarew** [comment]
> shorten up runProcess, ==> `run('dart', ['--version'])`

sgtm!

> and have a Dart.run. `Dart.run('tool/foo.dart')`

also sgtm!

These are changes which we'd easily be able to deprecate the older method, and forward through to the newer ones. So, a it could be a relatively painless transition for users.
