### ISSUE TITLE
Return List<PubApp> from Pub.global.list, add PubApp.version, remove AppVersion class

### ISSUE THREAD

**Issue by seaneagan** [google/grinder.dart#166]

**Comment by seaneagan** [comment]
@devoncarew Would you be ok with just making `Pub.global.list` private (`Pub.global._list`) for 0.7.0?  Then we can add it in 0.7.1 with the behavior described above.

**Comment by seaneagan** [comment]
And `AppVersion` -> `_AppVersion`.

**Comment by devoncarew** [comment]
Sounds good -
