### ISSUE TITLE
Incorrect command-line usage in README

### ISSUE THREAD

**Issue by seaneagan** [google/grinder.dart#169]
The README currently references `pub global run grind` which does not work.

The following all work:

`pub global activate grinder` followed by:

`grind`
`pub global run grinder`
`pub global run grinder:grind`
`pub global run grinder:grinder`

or bypass `pub global activate grinder` and just run:

`pub run grinder:grind`
`pub run grinder:grinder`
`pub run grinder` ([will work in dart 1.10](http://dartbug.com/22129))

IMO we should recommend both of the following:

* `pub run grinder:grind` (`pub run grinder` once dart 1.10 is released).  It's a single command, guarantees grinder version compatibility with the local package, and avoid global system state.
* `pub global activate` / `grind`.  It's really terse to run, and will allow for tab completion (#98).

**Comment by devoncarew** [comment]
I like `pub global activate grinder` + `grind` for terseness. 

We should list `pub run grinder:grind` ( / `pub run grinder`) as well, and prefer the 2nd one.

**Comment by seaneagan** [comment]
Fixed by #176.
