### ISSUE TITLE
Support subproject in tool

### ISSUE THREAD

**Issue by zoechi** [google/grinder.dart#171]
I was brooding about the dependency conflicts caused by dependencies added by Grinder for a while.
If Grinder would support having a package inside the `tool` directory instead of just a script then this package could have its own pubspec.yaml with its own dependencies completely independent of the package it is used on.
I have seen that the Dart team has fixed issues caused by nested projects in the past, therefore I think this scenario is supported.
I haven't tried to publish such a package to pub.dartlang.org yet though.
What do you think?

See also https://groups.google.com/a/dartlang.org/forum/#!topic/misc/H-9xOzA59rE

**Comment by seaneagan** [comment]
I don't think there's anything for grinder to do here, it would need to be supported at the pub level, and the bug for that is [here](http://dartbug.com/21920).

**Comment by zoechi** [comment]
The idea was that grinder not only looks for tool/grind.dart but also for tool/grind/tool/grind.dart where tool/grind/pubspec.yaml defines the subproject. Just an idea.

**Comment by seaneagan** [comment]
In order for `pub run grinder` to work, grinder would need to be in the root pubspec anyways.  And not supporting that would be confusing, and it also has some advantages over `pub global activate grinder`/`grind`, so I think we should at least give users the choice.

We can revisit If pub ever gets native support for nested packages.
