### ISSUE TITLE
Automatically add grinder to `dev_dependencies` on grinder:init

### ISSUE THREAD

**Issue by zoechi** [google/grinder.dart#180]
on 
```bash
pub global run grinder:init
```

**Comment by seaneagan** [comment]
Generally, it's intended to be used as `pub run grinder:init` (without global).  That way you can specify which version of grinder you want for a given project, and initialize a grinder script which works with it.  Den can help here though:

```
pub global activate stagehand
pub global activate den

stagehand package
den install grinder --dev
pub get
pub run grinder:init
```

:)
