### ISSUE TITLE
`pub global run grinder:init`/`pub run grinder:init` fails 

### ISSUE THREAD

**Issue by zoechi** [google/grinder.dart#181]
```bash
pub global run grinder:init
```
    Could not find bin/init.dart.

```bash
pub run grinder:init` fails
```
    Could not find bin/init.dart in package grinder.

**Comment by devoncarew** [comment]
Are you using a -dev release or the last stable one? It's not in stable yet -

**Comment by zoechi** [comment]
While playing around I switched back to stable and forgot about it.
Sorry for the noise.
