### ISSUE TITLE
Will grinder wait until futures complete in a task?

### ISSUE THREAD

**Issue by sethladd** [google/grinder.dart#185]
I am using grinder pre-0.7. Some of my tasks call methods that return a future. How do I know that grinder will wait for my futures to complete, before exiting?

**Comment by devoncarew** [comment]
Yup, if your task returns a future, grinder will wait on that future to complete before running the next task.

**Comment by devoncarew** [comment]
It's why the return type for a task is not specified; it could be `void` or `Future`.

**Comment by sethladd** [comment]
Gotcha, thanks!

**Comment by seaneagan** [comment]
Union types will be nice here `Future | Null`.
