### ISSUE TITLE
rename grinder?

### ISSUE THREAD

**Issue by devoncarew** [google/grinder.dart#186]
Tracking issue to potentially rename grinder. This would impact:

- the package name changes
- the commands to run change
- the entrypoint name changes (void main(args) => grind(ags))
- the user's script name changes (tool/grind.dart)

**Comment by zoechi** [comment]
I use it in a few of my packages already but I wouldn't mind. 
Any name suggestions?

**Comment by devoncarew** [comment]
Probably not going to happen now.
