### ISSUE TITLE
have tasks print out their execution time when finished?

### ISSUE THREAD

**Issue by devoncarew** [google/grinder.dart#197]
So:
```
[test-cli]
  running tests: test/all.dart...
  dart test/all.dart
  ...
  PASS: Lines getLineForOffset
  PASS: Lines offsetForLine
  
  All 13 tests passed.
  unittest-suite-success
  [0.160 seconds]

finished in 0.175 seconds.
```

**Comment by sethladd** [comment]
Funny. I just wrote a wrapper for this for one of my grinder tasks. How about @Timed as an annotation.

**Comment by seaneagan** [comment]
Would be sweet to have a live timer as a task runs as well, as a a sticky footer.  It could show milliseconds (possibly only updating every 10 milliseconds or something) until it reaches 1 second at which point it only shows seconds e.g. "00:00.000", "00:00.010", ..., "00:01", "00:02", ...

It could potentially show both the overall time, and the current task time.

**Comment by sethladd** [comment]
A live timer would be sweet. But in the meantime, +1 to displaying the run time for a task, per task. :)

**Comment by zoechi** [comment]
Grinder seems to do that already (like shown in @devoncarew s comment) but if the task does some async execution and the task returns a future it doesn't wait for it to complete.

```
grinder running [dind-clean]

[dind-clean]

finished in 0.074 seconds.
```
but the task actually took about 30 secs.
