### ISSUE TITLE
Missing a publish command on Pub

### ISSUE THREAD

**Issue by sethladd** [google/grinder.dart#203]
Should there be a publish() command on Pub object?

**Comment by devoncarew** [comment]
For completeness perhaps? For myself, that's something I'd be more comfortable with running manually.

**Comment by zoechi** [comment]
The `pubs` packages can be used for one step of this. I don't know what `publish` should include though.

**Comment by devoncarew** [comment]
PRs welcome. `pubs` sounds good as well as a solution.
