### ISSUE TITLE
Refactor file path shortcuts

### ISSUE THREAD

**Issue by seaneagan** [google/grinder.dart#206]
Do we need the following?

`WEB_DIR`, `LIB_DIR`, `BUILD_DIR`, `BIN_DIR`, `dartVM`.

The names all violate the style guide, which would suggest:

`webDir`, `libDir`, `buildDir`, `binDir`, `dartVm`

The dirs could make sense as part of a class which represents a pub package:

```
class Package {
  Directory get lib => new Directory('lib');
  Directory get bin => new Directory('bin');
  Directory get test => new Directory('test');
  Directory get web => new Directory('web');
  Directory get build => new Directory('build');
  // Anything else here?
}

Package package => new Package();
```

`dartVm` could make sense as part of #204:

`vm.path`

**Comment by devoncarew** [comment]
They're used as shorthand to access common project locations in build scripts. The pre-date the style guide change. They could be deprecated and replaced with `webDir, libDir, buildDir, binDir, dartVm`. They don't represent any general package, but the paths for the current one (the one the build script is running in). So I'd say  we should keep accessing them terse (just `buildDir`, not `currentPackage.buildDir`).

**Comment by seaneagan** [comment]
top-level `webDir` etc. sgtm.  I think `dartVM` will probably no longer be needed after #204 is resolved.

**Comment by seaneagan** [comment]
Do we want to add `testDir`, `toolDir` then?
