### ISSUE TITLE
Please make _sdkBin public

### ISSUE THREAD

**Issue by sethladd** [google/grinder.dart#215]
I'd like to work around an issue, by running `dart` myself with all the proper args. The `_sdkBin` seems perfect for running a command that can be found in the SDK.

However, it's private :(

Can we make it public? :)

**Comment by devoncarew** [comment]
Perhaps have an DartSdk class which exposes things like common directories and the various tools (and a `bin/` tool runner)?

**Comment by sethladd** [comment]
Sgtm

**Comment by devoncarew** [comment]
done: `sdkBin`
