### ISSUE TITLE
Upgrade to dart 1.9.0 to use async-await

### ISSUE THREAD

**Issue by seaneagan** [google/grinder.dart#218]
@devoncarew since grinder is a dev dependency and 1.10 is now released, are we ok to change the sdk constraint to `>=1.9.0 <2.0.0` and start using async-await?

**Comment by devoncarew** [comment]
I think so; as you say, both 1.9 and 1.10 are out. People who need 1.8 support have the published 0.7.0 version of grinder available -

**Comment by devoncarew** [comment]
done
