### ISSUE TITLE
Does PubApp.local('test') run in checked mode?

### ISSUE THREAD

**Issue by sethladd** [google/grinder.dart#252]
If so, is that just the default? What if I don't want checked mode? (just curious)

**Comment by zoechi** [comment]
I think this is blocked by 
- http://dartbug.com/16122
or
- http://dartbug.com/21821, 
- http://dartbug.com/21791

**Comment by sethladd** [comment]
Answer is no. And yes, https://code.google.com/p/dart/issues/detail?id=21791 is the one to follow.
