### ISSUE TITLE
feature / custom cmdline arguments

### ISSUE THREAD

**Issue by MikeMitterer** [google/grinder.dart#262]
Please support custom arguments

Something like this:

Sample:
grind --prefix-name Mike build

grind.dart
@Task()
showArgs() {
    customArgs().forEach((final String arg) => log(arg));
}

**Comment by zoechi** [comment]
I guess this is what #175 asks for.

**Comment by seaneagan** [comment]
yep, see #175, and #116 is for a specific impl of that.
