### ISSUE TITLE
Document reusable task defs via `export`

### ISSUE THREAD

**Issue by zoechi** [google/grinder.dart#263]
I have a bunch of tasks I want to reuse in every package.
It seems I have to declare tasks in the main library though.

Currently I have a shared package which contains a library with task definitions like
```Dart
const analyzeDesc = const Task('Run analyzer');
analyzeTask() { ...}
```

which I can use like 
```Dart
import 'package:bwu_utils_dev/grinder/default_tasks.dart';
main(List<String> args) => grind(args);
@analyzeDesc analyze() => analyzeTask();
```

I would prefer just 
```Dart
import 'package:bwu_utils_dev/grinder/default_tasks.dart' show main, analyze, test, ...;
// specify custom tasks here
```

I could probably just move `main()` to `package:bwu_utils_dev/grinder/default_tasks.dart` and export it but this makes it difficult to overwrite specific tasks where I don't want to use the default task.

Did I miss something? Other ideas?

**Comment by seaneagan** [comment]
> I would prefer just
> `import 'package:bwu_utils_dev/grinder/default_tasks.dart' show main, analyze, test, ...;`

grinder looks at all exported members of the entry point library, so you can just use `export`:

`export 'package:bwu_utils_dev/grinder/default_tasks.dart' show main, analyze, test, ...;`

changing this to a request for documentation of this feature.

**Comment by zoechi** [comment]
This is perfect :)

**Comment by zoechi** [comment]
Is it possible that `hide` is not respected?

I try to replace a task from the shared library with a custom task

```Dart
library bwu_dart_archive_downloader.tool.grind;

export 'package:bwu_utils_dev/grinder/default_tasks.dart'
    hide testWeb, test, check;
import 'package:bwu_utils_dev/grinder/default_tasks.dart'
    hide testWeb, test, check;

@Task('Runn all tests')
test() => testTask(['vm']);

@DefaultTask('Check everything')
@Depends(analyze, checkFormat, lint, test)
check() => checkTask();
```
but I get 
> Task `check` references dependency task `test` from library `bwu_utils_dev.grinder.default_tasks` which this build file does not export.

I expected `check`, and `test` from `default_tasks.dart` to be hidden.

Check looks exactly the same in `default_tasks.dart` but I had to override it because it references `test` from `default_task.dart` which I want to override.
Code-navigation from `test` in the `@Depends` annotation navigates to the `test` task shown above as expected.

Any ideas?

**Comment by seaneagan** [comment]
Hmm, there's a test for it:

https://github.com/google/grinder.dart/blob/03aa8d08ee97478236b490465764b77966f6194f/test/src/discover_tasks_test.dart#L154

Here's the code that's supposed to take care of it:

https://github.com/google/grinder.dart/blob/03aa8d08ee97478236b490465764b77966f6194f/lib/src/utils.dart#L90

Could also be #261 but looking at your code I don't think so.

**Comment by zoechi** [comment]
Thanks for the info! I'll investigate.

**Comment by seaneagan** [comment]
oops, I meant #264.

**Comment by zoechi** [comment]
Sorry, this was my mistake. There was another task with a dependency to `test`.

**Comment by zoechi** [comment]
This isn't an issue anymore. Seems I did something wrong.
