### ISSUE TITLE
Weird issue with `InstanceMirror of _Future` returned from `task.execute()`

### ISSUE THREAD

**Issue by zoechi** [google/grinder.dart#265]
Some explanation why I do what I do:
I have a package with Grinder tasks I share between different packages.
To be able to override specific tasks I use the following strategy

```Dart
@Task('Do something')
some() => someTask();

Function someTask = someTaskImpl;

someTaskImpl() => doSomethingAsync();
```
This looks a bit cumbersome but it's the easiest way I found to be able to customize single tasks while still being able to use the tasks in `@Depends(  ...needsToBeConst... )` annotations.

A default `tool/grind.dart` has just this line

```Dart
export 'package:bwu_utils_dev/grinder/default_tasks.dart' hide main;
```
or if I want to customize a few more
```Dart
library bwu_utils_dev.tool.grind;

export 'package:bwu_utils_dev/grinder/default_tasks.dart' hide main;
import 'package:bwu_utils_dev/grinder/default_tasks.dart' hide main;

main(List<String> args) {
  someTask = () => print('Hello, World');
  grind(args);
}
```

Now I run into the problem that `var result = task.execute(context);` returns `InstanceMirror of _Future` which results in Grinder not waiting for the async execution to complete.

It doesn't look like this is caused by Grinder (I might have overlooked something of course). To me it looked more like a zones bug but wasn't able to track the root cause down.
Changing `_executeTask` like below fixed it for me. 
I'll create a pull request but maybe you might have a better solution.

(code from https://github.com/google/grinder.dart/blob/master/lib/grinder.dart#L400)

```Dart
Future _executeTask(GrinderTask task) {
    log('${task}');

    GrinderContext context = new GrinderContext._(this, task);
    var result = task.execute(context);

    if (!(result is Future)) {
      if (result is InstanceMirror && result.reflectee is Future) {
        result = result.reflectee;
      } else {
        result = new Future.value(result);
      }
    }

    // TODO: whenComplete(), dispose of the context?
    return (result as Future).then((_) {
      log('');
    });
  }
```

**Comment by seaneagan** [comment]
The problem is here:

https://github.com/google/grinder.dart/blob/master/lib/src/discover_tasks.dart#L76
https://github.com/google/grinder.dart/blob/master/lib/src/discover_tasks.dart#L78

both need to append `.reflectee` to the return value, and of course we should add a test for this.
