### ISSUE TITLE
Consider delete() instead of deleteEntity()

### ISSUE THREAD

**Issue by sethladd** [google/grinder.dart#36]
`deleteEntity(new Directory('path'))` is a bit verbose. What do you think about `delete(string_or_directory)` ?

**Comment by seaneagan** [comment]
I like overloads because because once we get [union types](http://dartbug.com/4938) the type checking can be reinstated.

**Comment by seaneagan** [comment]
I think this is done.  Filed #138 to track removing deprecated things later on.
