### ISSUE TITLE
publish null-safe package version

### ISSUE THREAD

**Issue by pq** [google/grinder.dart#369]
It looks like the API is migrated or under-way.

@devoncarew : thoughts on publishing?

We'll want this for the linter (dart-lang/linter#2399).

Thanks!

**Comment by devoncarew** [comment]
Thanks for the ping! @nex3 did the migration work here :)

I'm happy to publish. From reading https://dart.dev/null-safety/migration-guide#step5-publish it looks like best practice is to bump to a new major version. The last published version was `0.8.6` and the version in master is `0.8.7-nullsafety.1`. I'll likely bump to something like `0.9.0-nullsafety.0` and publish.

**Comment by devoncarew** [comment]
I'm having trouble publishing due to the analyzer / test / glob cycle:

```
Package validation found the following error:
* Your pubspec.yaml must not override non-dev dependencies.
  This ensures you test your package against the same versions of its dependencies
  that users will have when they use it.
```

**Comment by devoncarew** [comment]
https://github.com/google/grinder.dart/blob/master/pubspec.yaml#L25

**Comment by devoncarew** [comment]
The solve issue could be related to https://github.com/dart-lang/sdk/issues/44577.

**Comment by jakemac53** [comment]
I don't believe the `test` package would be restricting this any longer - if you remove the override for `glob` do you still get resolution errors? Can you paste the output here?

**Comment by devoncarew** [comment]
Sure:

```
pub get
Resolving dependencies... 
The current Dart SDK version is 2.12.0-133.0.dev.

Because test >=1.16.0-nullsafety <1.16.0-nullsafety.7 requires SDK version >=2.10.0-0 <2.11.0 and test >=1.16.0-nullsafety.7
  <1.16.0-nullsafety.10 depends on analyzer >=0.36.0 <0.41.0, test >=1.16.0-nullsafety <1.16.0-nullsafety.10 requires analyzer >=0.36.0
  <0.41.0.
And because test >=1.16.0-nullsafety.10 depends on analyzer >=0.36.0 <0.42.0 which depends on glob ^1.0.3, test >=1.16.0-nullsafety
  requires glob ^1.0.3.
So, because grinder depends on both glob ^2.0.0-nullsafety and test ^1.16.0-nullsafety, version solving failed.
```

**Comment by jakemac53** [comment]
Ah, so it looks to me like the issue is that `analyzer` needs to support the latest version of glob, which it actually does https://github.com/dart-lang/sdk/blob/master/pkg/analyzer/pubspec.yaml#L16. So maybe that just needs to be published.

**Comment by devoncarew** [comment]
Yeah, that constraint was just widened. Thanks for looking at this - good to hear that that change will likely unblock this publish.

**Comment by devoncarew** [comment]
Done
