### ISSUE TITLE
The convention for the bin/tool scripts is poorly explained

### ISSUE THREAD

**Issue by bgourlie** [google/grinder.dart#50]
The convention for the bin and tool scripts is poorly explained and it took me some tinkering before I was able to run tests using `pub run grinder tests`.

**Comment by seaneagan** [comment]
@devoncarew IMO It's still a bit confusing to have both `grinder` and `grind`.  In particular it would be nice to use the same name whether using `pub run` or not:

`pub run grinder`
`grind`

I prefer `grind`, but `pub run grind` would require changing the package name, which would mean deprecating the entire package, so I'd be fine having to run `grinder`.

**Comment by devoncarew** [comment]
Yeah, I have in the past argued that the main executable for a package should have the same name as a package. There's always reasons to do something different (`grinder` uses `grind`; `dart_style` uses `format`), but there's a lot of value to the users in just knowing what the main executable should be given the package name.

I'll do a bit more noodling on this.
