### ISSUE TITLE
Support a default target when none provided on command line

### ISSUE THREAD

**Issue by seaneagan** [google/grinder.dart#74]
Most build tools allow setting a default target/goal/task:

https://github.com/gulpjs/gulp/
http://gruntjs.com/creating-tasks
http://www.gnu.org/software/make/manual/make.html#Goals

which would allow new devs on the project to just run `grind`, without needing to know what targets the project supports.

Also, it would be cool if the default drone.io or travis script were just:

```shell
pub get
pub run grinder
```

so then you wouldn't need to configure it at all.

**Comment by devoncarew** [comment]
+1

**Comment by devoncarew** [comment]
As a tweak, I think If the user runs without any args, and a default target runs, I'll print out something like `run grinder -h for help and a list of valid tasks`. That'll let new users know how to get other available targets. Right now they can just see those by running w/o any args.
