### ISSUE TITLE
Pub.global should be static

### ISSUE THREAD

**Issue by seaneagan** [google/grinder.dart#77]
Currently `global` is the only instance field on `Pub`, so you have to do `new Pub().global.run(..)`.  I think it was inteneded to be static so you can do `Pub.global.run(..)`.

**Comment by devoncarew** [comment]
Hmm, yup.

**Comment by devoncarew** [comment]
Fixed: https://github.com/google/grinder.dart/commit/041e789cd16b4f3f53ee108157334baade00fd48
