### ISSUE TITLE
Use Zone value to access GrinderContext so it doesn't have to be passed around everywhere.

### ISSUE THREAD

**Issue by seaneagan** [google/grinder.dart#78]
* More convenient
* Less grinder lock in effect

**Comment by seaneagan** [comment]
I do something similar with `now` in https://pub.dartlang.org/packages/clock.

**Comment by devoncarew** [comment]
Makes sense. It's something to evaluate w/ a bunch of other breaking API changes.

**Comment by seaneagan** [comment]
@devoncarew What do you think about allowing task callbacks to either take a GrinderContext arg or not for awhile, but deprecate taking it, and eventually remove?

**Comment by devoncarew** [comment]
Yeah, sounds good to me. I like the idea of using Zones to have global-ish variables available to each running task. And your technique is backwards compatible, so it could be done at any time.

I do want to try and get a good picture of all potential API breaking changes, so we can make sure they all work well together, and they can be batched up into as few major version releases as possible.

**Comment by sethladd** [comment]
+1 to the idea of using Zone for a "thread local" context object.

**Comment by devoncarew** [comment]
https://github.com/seaneagan/clock/blob/master/lib/src/zoned_value.dart

**Comment by devoncarew** [comment]
done -
