### ISSUE TITLE
File-watching mode for running tasks in reaction to file system changes

### ISSUE THREAD

**Issue by sethladd** [google/grinder.dart#84]
Use case:

I want to run @kevmoo 's source_gen from grinder. Source_gen works best when it's watching a directory. I'd like to ask grinder to:

1. start up
1. start watching a directory
1. when a directory and its files change, run a task

**Comment by devoncarew** [comment]
Hmm, all good questions. I'll have to create a github label for 'potential API redesign motivator'

**Comment by devoncarew** [comment]
going to close this one out
