### ISSUE TITLE
Support rename refactoring for task dependencies.

### ISSUE THREAD

**Issue by seaneagan** [google/grinder.dart#91]
If the dependency links directly back to the declaration:

```dart
@Task()
init() {}

@Task(depends: const [init])
compile() {}
```

Then `init` can be renamed safely and conveniently using editor rename refactoring.

Also, `init` is shorter than `'init'`.

Will still need to support e.g. `'init'` as well for programmatic use cases.

**Comment by devoncarew** [comment]
I'm not normally a fan of un-typed method params, but if we make `depends` dynamic, we could support:
- a list of strings
- a list of function literals
- a single string with names of tasks (`'foo bar'`)

**Comment by seaneagan** [comment]
The `const ` part is annoying, but hopefully it will [become unnecessary](http://dartbug.com/4046), at which point the `'foo bar'` form wouldn't save much:

```dart
@Task(depends: 'foo bar')
@Task(depends: [foo, bar])
```

We could at least type it as `List` then.  But most people will probably be creating their grinder files from examples, or #76, so they will probably just copy the format that those use.

**Comment by seaneagan** [comment]
Started working on this.  I realized a couple other niceties of this:

* allow one to link to tasks defined in other libraries!
* dart editor and others have the nice feature of clicking on a variable and immediately being shown all the places it is used in the current file.  that will allow for quickly seeing all the places where a task is used as a dependency!
