### ISSUE TITLE
Allow default task to have any name

### ISSUE THREAD

**Issue by seaneagan** [google/grinder.dart#92]
Instead of:

```dart
@Task(name: 'default', depends: const ['deploy', 'docs'])
_default() {}
```

```dart
@DefaultTask(depends: const ['deploy', 'docs'])
all() {}
```

Do we want to remove the `name` parameter from `@Task` then?  So far I only needed it because `default` is a keyword in dart.

For programmatic use cases, we'll probably also want a `Grinder.defaultTask` property which can only be assigned to once.  Maybe also expose this as a top-level `defaultTask` property.  Or add a `bool asDefault: false` param to `addTask`.

**Comment by devoncarew** [comment]
+1 to removing the `name` param - renaming tasks from their function name probably isn't a common or critical use case.
