### ISSUE TITLE
Ability to opt out of annotated task scanning

### ISSUE THREAD

**Issue by seaneagan** [google/grinder.dart#93]
I can't imagine scanning taking that long, but maybe just to be explicit that one does not want to define tasks using annotations, they may want to opt out.

They can already do this by using `startGrinder` explicitly instead of `grind`.

But, it may be more clear what's going on if we deprecate `startGrinder`, and instead add an optional named parameter to `grind` to opt out:

`main(args) => grind(args, scan: false)`

**Comment by devoncarew** [comment]
Yeah, I only see disabling scanning as an escape hatch in case there are tasks defined you don't want. So, a pretty infrequent operation.
