### ISSUE TITLE
Tab completion for tasks

### ISSUE THREAD

**Issue by seaneagan** [google/grinder.dart#98]
It would be really cool to be able to tab-complete task names on the command line.  This would be super easy to do using [unscripted](https://pub.dartlang.org/packages/unscripted).

**Comment by seaneagan** [comment]
`grind completion install`

```shell
$ grind [TAB]
init
compile
deploy
all

$ grind d[TAB]
$ grind deploy
```

**Comment by devoncarew** [comment]
I didn't realize this was available; looks great!

**Comment by sunglim** [comment]
+1 , `unscripted` is awesome!
